[package]
edition = "2021"
name = "difference-of-squares"
version = "1.2.0"

[dependencies]

[lib]
name = "difference_of_squares"
path = "src/lib.rs"

[[bin]]
name = "difference-of-squares"
path = "src/main.rs"
